
  CREATE TABLE "RDMP"."T_SLEEP_TRACE" 
   (	"ID" NUMBER, 
	"YGBH" NUMBER, 
	"TIME" DATE, 
	"CONTENT" CLOB, 
	"TYPE" NUMBER, 
	"CUSTOM" NUMBER, 
	"ASSIGNID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "RDMP" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "RDMP" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;

   COMMENT ON COLUMN "RDMP"."T_SLEEP_TRACE"."YGBH" IS '跟进人编号';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_TRACE"."TIME" IS '跟进事件';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_TRACE"."CONTENT" IS '跟进内容';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_TRACE"."TYPE" IS '跟进方式';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_TRACE"."CUSTOM" IS '客户id';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_TRACE"."ASSIGNID" IS '分配记录id';
