
  CREATE TABLE "RDMP"."T_SLEEP_ASSIGN" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ASSIGNEE" NUMBER(*,0), 
	"ASSIGNOR" NUMBER(*,0), 
	"CUSTOM" NUMBER(*,0), 
	"STATUS" NUMBER(*,0), 
	"RULE" NUMBER(*,0), 
	"CREATEAT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "RDMP" ;

   COMMENT ON COLUMN "RDMP"."T_SLEEP_ASSIGN"."ASSIGNEE" IS '被分配员工';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_ASSIGN"."ASSIGNOR" IS '分配员工';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_ASSIGN"."CUSTOM" IS '客户号';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_ASSIGN"."STATUS" IS '分配状态';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_ASSIGN"."RULE" IS '分配规则 1 开发关系 2 服务关系 3 随机 4 指定';


  create sequence RDMP.SEQ_SLEEP
  minvalue 1
  maxvalue 999999999999999
  start with 1
  increment by 1
  nocache;