
  CREATE TABLE "RDMP"."T_SLEEP_LABEL" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"STATUS" NUMBER, 
	"TYPE" NUMBER, 
	"YGBH" NUMBER, 
	"CREATEAT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "RDMP" ;

   COMMENT ON COLUMN "RDMP"."T_SLEEP_LABEL"."NAME" IS '标签名';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_LABEL"."STATUS" IS '标签状态';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_LABEL"."TYPE" IS '标签类型';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_LABEL"."YGBH" IS '标签创建人';
   COMMENT ON COLUMN "RDMP"."T_SLEEP_LABEL"."CREATEAT" IS '创建时间';
